export const ADD_DATA = 'ADD_DATA'
export const GET_DATA = "GET_DATA"
export const GET_SEARCH = "GET_SEARCH"
export const EDIT_DATA = "EDIT_DATA"
export const GET_DATA_PAGINATION = "GET_DATA_PAGINATION"
export const GET_SLICE_DATA = "GET_SLICE_DATA"
export const SET_OFFSET = "SET_OFFSET"
export const GET_QUERY_DATA = "GET_QUERY_DATA"
export const SET_CHANGE_PASSWORD ="SET_CHANGE_PASSWORD"

//child operation
export const GET_ALL_CHILD_DATA = "GET_ALL_CHILD_DATA"
export const GET_CHILD_DATA = "GET_CHILD_DATA"
export const EDIT_CHILD_DATA = "EDIT_CHILD_DATA"

//ClassList Action
export const GET_CLASS_LIST_DATA = "GET_CLASS_LIST_DATA"
export const GET_SLICE_CLASS_LIST_DATA = "GET_SLICE_CLASS_LIST_DATA"

//StaffList Action
export const GET_STAFF_LIST_DATA = "GET_STAFF_LIST_DATA"
export const GET_SLICE_STAFF_LIST_DATA = "GET_SLICE_STAFF_LIST_DATA"
export const ADD_STAFF_DATA = "ADD_STAFF_DATA"